Update changelog for razor insertion
dotnet/vscode-csharp pull request #7228
Opened 2024-06-13 00:10 UTC by ryzngard

2024-06-13 00:56 UTC, davidwengier approved these changes

2024-06-13 02:37 UTC, dibarbet requested changes

2024-06-13 02:37 UTC, dibarbet commented on CHANGELOG.md
> +* Update Razor to 9.0.0-preview.24311.4 (PR: [#7225](https://github.com/dotnet/vscode-csharp/pull/7225))
This needs to be in a new section, with the current latest renamed to 2.34.10 (it hasn't been updated since the prerelease)

2024-06-14 20:26 UTC, dibarbet approved these changes

2024-06-14 21:30 UTC, merged